[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "myfs"
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
	"dvc[ssh] >= 2.27.0",
]

[project.entry-points."fsspec.specs"]
gchapero = "myfs:MyFileSystem"
